const recargar = document.getElementById('btn');
recargar.addEventListener('click', actualizarPagina);

const frase = document.getElementById('frase');
frase.innerHTML = '';

var a = Math.floor(Math.random() * 100 + 1);
console.log(a);


function actualizarPagina(){
    location.reload();
}

switch (a) {
    case 1: frase.innerHTML = 'Recuerda que no puedes fallar en ser tú mismo' + '<br>' + '(Wayne Dyer)';
        break;
    case 2: frase.innerHTML = 'Siempre es temprano para rendirse' + '<br>' + ' (Jorge Álvarez Camacho)';
        break;
    case 3: frase.innerHTML = 'Sólo una cosa convierte en imposible un sueño: el miedo a fracasar' + '<br>' + ' (Paulo Coelho)';
        break;
    case 4: frase.innerHTML = 'Lo que haces hoy puede mejorar todos tus mañanas' + '<br>' + ' (Ralph Marston)';
        break;
    case 5: frase.innerHTML = 'Las pequeñas acciones de cada día hacen o deshacen el carácter' + '<br>' + ' (Oscar Wilde)';
        break;
    case 6:  frase.innerHTML = 'Cáete siete veces y levántate ocho' + '<br>' + ' (Proverbio japonés)';
        break;
    case 7: frase.innerHTML = 'Para que los cambios tengan un valor verdadero deben ser consistentes y duraderos' + '<br>' + ' (Anthony Robbins)';
        break;
    case 8: frase.innerHTML = 'Nada sucede hasta que algo se mueve' + '<br>' + ' (Albert Einstein)';
        break;
    case 9: frase.innerHTML = 'Ser un buen perdedor es aprender cómo ganar' + '<br>' + ' (Carl Sandburg)';
        break;
    case 10: frase.innerHTML = 'Todos nuestros sueños pueden hacerse realidad, si tenemos el coraje de perseguirlos' + '<br>' + '(Walt Disney)';
        break;
    case 11: frase.innerHTML = 'Quien se transforma a sí mismo, transforma el mundo' + '<br>' + '(Dalai Lama)';
        break;
    case 12: frase.innerHTML = 'Tu tiempo es limitado, así que no lo malgastes viviendo la vida de alguien más… ten el valor de seguir tu corazón y tu intuición' + '<br>' + '(Steve Jobs)';
        break;
    case 13: frase.innerHTML = 'La mayoría de las personas gastan más tiempo y energías en hablar de los problemas que en afrontarlos' + '<br>' + ' (Henry Ford)';
        break;
    case 14: frase.innerHTML = 'No es que tengamos poco tiempo, es que perdemos mucho' + '<br>' + ' (Séneca)';
        break;
    case 15: frase.innerHTML = 'Para poder triunfar, tu deseo de tener éxito debe ser mayor que tu miedo a fracasar' + '<br>' + ' (Bill Cosby)';
        break;
    case 16: frase.innerHTML = 'El verdadero buscador crece y aprende, y descubre que siempre es el principal responsable de lo que sucede' + '<br>' + ' (Jorge Bucay)';
        break;
    case 17: frase.innerHTML = 'Si la oportunidad no llama a tu puerta, construye una puerta' + '<br>' + ' (Milton Berle)';
        break;
    case 18: frase.innerHTML = 'Siempre hay una mejor manera de hacerlo, encuéntrala' + '<br>' + ' (Thomas A. Edison)';
        break;
    case 19: frase.innerHTML = 'Nunca es demasiado tarde para ser la persona que podrías haber sido' + '<br>' + ' (George Eliot)';
        break;
    case 20: frase.innerHTML = 'Cuando ya no somos capaces de cambiar una situación, tenemos el reto de cambiarnos a nosotros mismos' + '<br>' + ' (Viktor Frankl)';
        break;
    case 21: frase.innerHTML = ' La derrota no es derrota hasta que es aceptada como una realidad en tu propia mente' + '<br>' + ' (Bruce Lee)';
        break;
    case 22: frase.innerHTML = 'Es duro fracasar, pero es todavía peor no haber intentado nunca triunfar' + '<br>' + ' (Theodore Roosevelt)';
        break;
    case 23: frase.innerHTML = 'La felicidad está escondida en la sala de espera de la felicidad' + '<br>' + ' (Eduard Punset)';
        break;
    case 24: frase.innerHTML = 'La confianza en sí mismo es el primer secreto del éxito' + '<br>' + ' (Ralph Waldo Emerson)';
        break;
    case 25: frase.innerHTML = 'El hombre bien preparado para la lucha ya ha conseguido medio triunfo' + '<br>' + ' (Miguel de Cervantes)';
        break;
    case 26: frase.innerHTML = 'Sabemos lo que somos, pero no sabemos lo que podemos ser' + '<br>' + ' (William Shakespeare)';
        break;
    case 27: frase.innerHTML = 'La vida comienza al final de la zona de confort' + '<br>' + ' (Neale Donald Walsch)';
        break;
    case 28: frase.innerHTML = 'Cualquiera que no esté cometiendo errores es que no está intentándolo lo suficiente' + '<br>' + ' (Wess Roberts)';
        break;
    case 29: frase.innerHTML = 'Debes hacer las cosas que piensas que no puedes hacer' + '<br>' + ' (Eleanor Roosevelt)';
        break;
    case 30: frase.innerHTML = 'Confiar en ti mismo no garantiza el éxito, pero no hacerlo garantiza el fracaso' + '<br>' + ' (Albert Bandura)';
        break;
    case 31: frase.innerHTML = 'El mayor error que una persona puede cometer es tener miedo de cometer un error' + '<br>' + ' (Elbert Hubbard)';
        break;
    case 32: frase.innerHTML = 'De una pequeña semilla un poderoso tronco puede crecer' + '<br>' + '(Esquilo)';
        break;
    case 33: frase.innerHTML = 'La única manera de encontrar los límites de lo posible es ir más allá de lo imposible' + '<br>' + ' (Arthur C. Clarke)';
        break;
    case 34: frase.innerHTML = 'Cuando la vida te ofrezca un limón, exprímelo y haz limonada ' + '<br>' + '(Clement Stone)';
        break;
    case 35: frase.innerHTML = 'La medida de lo que somos es lo que hacemos con lo que tenemos' + '<br>' + ' (Vince Lombardi)';
        break;
    case 36: frase.innerHTML = 'Nos convertimos en lo que pensamos' + '<br>' + ' (Earl Nightingale)';
        break;
    case 37: frase.innerHTML = 'Solo aquellos que se atreven a tener grandes fracasos terminan consiguiendo grandes éxitos' + '<br>' + ' (Robert F. Kennedy)';
        break;
    case 38: frase.innerHTML = 'El poder de la imaginación nos hace infinitos' + '<br>' + ' (John Muir)';
        break;
    case 39: frase.innerHTML = 'Antes que nada, la preparación es la llave del éxito' + '<br>' + ' (Alexander Graham Bell)';
        break;
    case 40: frase.innerHTML = 'El mejor modo de predecir el futuro es inventándolo' + '<br>' + ' (Alan Key)';
        break;
    case 41: frase.innerHTML = 'Las cosas no se dicen, se hacen, porque al hacerlas se dicen solas' + '<br>' + ' (Woody Allen)';
        break;
    case 42: frase.innerHTML = 'Dale luz y la oscuridad desaparecerá por sí mismo ' + '<br>' + '(Erasmo)';
        break;
    case 43: frase.innerHTML = 'Para aumentar nuestro grado de autoestima, primero debemos aprender a vivir conscientemente, porque este es nuestro fundamento de todo' + '<br>' + ' (Nathaniel Branden)';
        break;
    case 44: frase.innerHTML = 'El problema es que piensas que tienes tiempo' + '<br>' + ' (Buda)';
        break;
    case 45: frase.innerHTML = 'Una persona con una nueva idea es una broma hasta que la idea tiene éxito' + '<br>' + ' (Mark Twain)';
        break;
    case 46: frase.innerHTML = 'Si de veras desear ver al Creador, conviértete en un creador' + '<br>' + ' (Deepak Chopra)';
        break;
    case 47: frase.innerHTML = 'No se sale adelante celebrando éxitos sino superando fracasos' + '<br>' + ' (Orison Swett Marden)';
        break;
    case 48: frase.innerHTML = 'El miedo puede paralizar, dominar, aislar, pero ante un atisbo de valentía cederá terreno rápidamente' + '<br>' + ' (Jose Antonio Marina).';
        break;
    case 49: frase.innerHTML = 'Tener éxito no es aleatorio; es una variable dependiente del esfuerzo' + '<br>' + ' (Sófocles)';
        break;
    case 50: frase.innerHTML = 'El hombre necesita dificultades porque son necesarias para disfrutar del éxito' + '<br>' + ' (A.P.J. Abdul Kalam)';
        break;
    case 51: frase.innerHTML = 'Agudiza la percepción de todo lo que te hace sentir bien y recréate en ello' + '<br>' + ' (Martin Seligman)';
        break;
    case 52: frase.innerHTML = 'No te desanimes. A menudo la última llave que te queda por probar abre el candado.' + '<br>' + ' (Anónimo)';
        break;
    case 53: frase.innerHTML = 'No merece la pena vivir una vida sin examinar' + '<br>' + ' (Sócrates)';
        break;
    case 54: frase.innerHTML = 'Todo es crecimiento y aprendizaje, un crecimiento continuo' + '<br>' + ' (Brian Weiss)';
        break;
    case 55: frase.innerHTML = 'Siempre estoy haciendo cosas que no sé hacer, de manera que tengo que aprender como hacerlo' + '<br>' + ' (Pablo Picasso)';
        break;
    case 56: frase.innerHTML = 'Un líder es alguien que conoce el camino, lo recorre y lo muestra' + '<br>' + ' (John C.Maxwell)';
        break;
    case 57: frase.innerHTML = 'Todos los éxitos resultan de trabajar y saber perseverar' + '<br>' + ' (Og Mandino)';
        break;
    case 58: frase.innerHTML = 'Cuando está muy oscuro puedes ver las estrellas' + '<br>' + ' (Proverbio persa)';
        break;
    case 59: frase.innerHTML = 'El mayor placer de la vida es hacer lo que la gente dice que no puedes hacer' + '<br>' + ' (Walter Bagehot)';
        break;
    case 60: frase.innerHTML = 'El éxito es conseguir lo que quieres. La felicidad, es querer lo que ya has conseguido' + '<br>' + ' (Lair Ribeiro)';
        break;
    case 61: frase.innerHTML = 'Puedes hacer cualquier cosa pero no puedes hacerlo todo' + '<br>' + ' (David Allen)';
        break;
    case 62: frase.innerHTML = 'Solo yo puedo cambiar mi vida. Nadie puede hacerlo por mí' + '<br>' + ' (Carol Burnett)';
        break;
    case 63: frase.innerHTML = 'El noventa por ciento de todos los que fallan, no están realmente derrotados; sencillamente se dan por vencidos' + '<br>' + ' (Paul J. Meyer)';
        break;
    case 64: frase.innerHTML = 'Siempre parece imposible … hasta que se hace' + '<br>' + ' (Nelson Mandela)';
        break;
    case 65: frase.innerHTML = 'Todo hombre muere. No todo hombre vive' + '<br>' + ' (William Wallace)';
        break;
    case 66: frase.innerHTML = 'Nada en la vida debe ser temido, solamente comprendido. Es hora de comprender más y temer menos' + '<br>' + ' (Marie Curie)';
        break;
    case 67: frase.innerHTML = 'Somos lo que hacemos repetidamente. La excelencia, entonces, no es un acto sino un hábito ' + '<br>' + '(Aristóteles)';
        break;
    case 68: frase.innerHTML = 'La vida no es un problema a ser resuelto, sino una realidad a experimentar' + '<br>' + ' (Soren Kierkegaard)';
        break;
    case 69: frase.innerHTML = 'Solo es posible avanzar cuando se mira lejos. Solo cabe progresar cuando se piensa en grande' + '<br>' + ' (Ortega y Gasset)';
        break;
    case 70: frase.innerHTML = 'La victoria es más dulce cuando ya conociste la derrota' + '<br>' + ' (Malcolm Forbes)';
        break;
    case 71: frase.innerHTML = 'Lo que no te mata te hace más fuerte' + '<br>' + ' (Friedrich Nietzsche)';
        break;
    case 72: frase.innerHTML = 'Solo aquellos que se atreven a sufrir grandes fracasos son capaces de conseguir grandes éxitos' + '<br>' + ' (Will Smith)';
        break;
    case 73: frase.innerHTML = 'El verdadero emprendedor es un hacedor, no un soñador' + '<br>' + ' (Nolan Bushnell)';
        break;
    case 74: frase.innerHTML = 'Tienes que entrenar tu cerebro para ser positivo al igual que entrenas tu cuerpo' + '<br>' + ' (Shawn Achor)';
        break;
    case 75: frase.innerHTML = 'La fortaleza y crecimiento llegan solo a través de esfuerzo y lucha continuas' + '<br>' + ' (Napoleon Hill)';
        break;
    case 76: frase.innerHTML = 'Allí fuera, en algún garaje, hay un emprendedor forjando una bala con el nombre de tu compañía' + '<br>' + ' (Gary Hamel)';
        break;
    case 77: frase.innerHTML = 'Cuando tienes un sueño tienes que agarrarlo y nunca dejarlo ir' + '<br>' + ' (Carol Burnett)';
        break;
    case 78: frase.innerHTML = 'Mira de cerca al presente que estas construyendo, debería parecerse al futuro que estas soñando' + '<br>' + ' (Alice Walker)';
        break;
    case 79: frase.innerHTML = 'No sobreviven las especies más fuertes, ni las más inteligentes, sino las que mejor se adaptan al cambio' + '<br>' + ' (Darwin)';
        break;
    case 80: frase.innerHTML = 'Cuanto más hacemos, más podemos hacer' + '<br>' + ' (William Hazlitt)';
        break;
    case 81: frase.innerHTML = 'La vida no trata de encontrarte a ti mismo. La vida trata de crearte a ti mismo' + '<br>' + ' (George Bernard Shaw)';
        break;
    case 82: frase.innerHTML = 'La suerte es un dividendo del sudor. Cuanto más sudes, más suerte tendrás' + '<br>' + ' (Ray Kroc)';
        break;
    case 83: frase.innerHTML = 'La forma más efectiva de hacerlo, es hacerlo' + '<br>' + ' (Amelia Earhart)';
        break;
    case 84: frase.innerHTML = 'El significado de la vida es darle a la vida significado' + '<br>' + '(Ken Hudgins)';
        break;
    case 85: frase.innerHTML = 'La clave del éxito: querer ganar, saber perder ' + '<br>' + '(Nicolás de Maquiavelo)';
        break;
    case 86: frase.innerHTML = 'No puedes derrotar a la persona que nunca se rinde' + '<br>' + ' (Babe Ruth)';
        break;
    case 87: frase.innerHTML = 'Un sueño es solo un sueño. Una meta es un sueño con un plan y una fecha límite' + '<br>' + ' (Harvey Mackay)';
        break;
    case 88: frase.innerHTML = 'El éxito es una decisión. Decide lo que harás con tu vida u otra persona lo hará por ti' + '<br>' + ' (John Atkinson)';
        break;
    case 89: frase.innerHTML = 'Tienes que hacer que ocurra' + '<br>' + ' (Denis Diderot)';
        break;
    case 90: frase.innerHTML = 'La vida es una obra de teatro que no permite ensayos… Por eso, canta, ríe, baila, llora y vive intensamente cada momento de tu vida… Antes que el telón baje y la obra termine sin aplausos' + '<br>' + ' (Charles Chaplin)';
        break;
    case 91: frase.innerHTML = 'Si metes la pata no es culpa de tus padres ni de tus profesores, así que no lloriquees por tus errores y aprende de ellos' + '<br>' + ' (Bill Gates)';
        break;
    case 92: frase.innerHTML = 'No huyo de un reto porque tenga miedo. Al contrario, corro hacia el reto porque la única forma de escapar al miedo es arrollarlo con tus pies' + '<br>' + ' (Nadia Comaneci)';
        break;
    case 93: frase.innerHTML = 'Un buen plan imperfecto ejecutado hoy es mejor que un plan perfecto ejecutado mañana' + '<br>' + ' (General Patton)';
        break;
    case 94: frase.innerHTML = 'La determinación es el punto inicial de todo logro' + '<br>' + ' (W.Clement Stone)';
        break;
    case 95: frase.innerHTML = 'Lo que no se empieza nunca tendrá un final' + '<br>' + ' (Johann Wolfgang von Goethe)';
        break;
    case 96: frase.innerHTML = 'Elige un trabajo que te guste, y nunca tendrás que volver a trabajar en tu vida' + '<br>' + ' (Confucio)';
        break;
    case 97: frase.innerHTML = 'El mayor riesgo es no asumir ningún riesgo' + '<br>' + ' (Mark Zuckerberg)';
        break;
    case 98: frase.innerHTML = 'Puedo aceptar el fracaso, todos fracasan en algo. Pero no puedo aceptar no intentarlo' + '<br>' + ' (Michael Jordan)';
        break;
    case 99: frase.innerHTML = 'Uno de los mayores errores que comete la gente es intentar forzarse a tener interés por algo. Tú no eliges tus pasiones; tus pasiones te eligen a ti' + '<br>' + ' (Jeff Bezos)';
        break;
    case 100: frase.innerHTML = 'Hazlo, o no lo hagas, pero no lo intentes' + '<br>' + ' (Yoda)';
        break;
}
